name: campeones
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mne
  - mne-bids
  - neurokit2
  - scikit-learn
  - jupyterlab
  - matplotlib
  - pandas
  - numpy
  - seaborn
  - autoreject
  - pyprep
  - mne-icalabel
  - gitpython
  - pyxdf
  - mnelab
  - pywavelets
  - mkdocs-material
  - openpyxl
  - opencv
  - ipympl
  - ipywidgets
  - pip
  - pip:
    - glhmm
