#!/usr/bin/env python
"""Create MNE Epochs from CHANGE_PHOTO / NO_CHANGE_PHOTO events.

Implements Task 1.4 from the research diary.

For each run of a subject:
1. Loads the preprocessed EEG (.vhdr) from campeones_preproc
2. Loads the photo_events TSV generated by 22_generate_photo_events.py
3. Converts CHANGE_PHOTO and NO_CHANGE_PHOTO rows to an MNE events array
4. Creates Epochs centred on those events
5. Concatenates all runs and saves the result

Usage
-----
    python scripts/validation/23_epoch_photo_events.py --subject 27
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import mne
import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Paths & constants
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[1]

PREPROC_ROOT = PROJECT_ROOT / "data" / "derivatives" / "campeones_preproc"
PHOTO_EVENTS_ROOT = PROJECT_ROOT / "data" / "derivatives" / "photo_events"
RESULTS_ROOT = PROJECT_ROOT / "results" / "validation" / "photo_epochs"

SESSION = "vr"

EVENT_ID = {"CHANGE_PHOTO": 1, "NO_CHANGE_PHOTO": 2}

# Epoch window (seconds relative to event onset)
TMIN = -1.0
TMAX = 2.0
BASELINE = (-1.0, -0.5)

# Runs config (same as 22_generate_photo_events.py)
RUNS_CONFIG: dict[str, list[dict]] = {
    "27": [
        {"run": "002", "acq": "a", "task": "01"},
        {"run": "003", "acq": "a", "task": "02"},
        {"run": "004", "acq": "a", "task": "03"},
        {"run": "006", "acq": "a", "task": "04"},
        {"run": "007", "acq": "b", "task": "01"},
        {"run": "009", "acq": "b", "task": "03"},
        {"run": "010", "acq": "b", "task": "04"},
    ],
}

# 32 EEG channels
EEG_CHANNELS = [
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2',
    'F7', 'F8', 'T7', 'T8', 'P7', 'P8', 'Fz', 'Cz', 'Pz',
    'FC1', 'FC2', 'CP1', 'CP2', 'FC5', 'FC6', 'CP5', 'CP6',
    'FT9', 'FT10', 'TP9', 'TP10', 'FCz',
]


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def resolve_eeg_path(subject: str, task: str, acq: str, run: str) -> Path | None:
    """Return path to preprocessed .vhdr, or None if not found."""
    eeg_dir = (PREPROC_ROOT / f"sub-{subject}" / f"ses-{SESSION}" / "eeg")
    vhdr = eeg_dir / (
        f"sub-{subject}_ses-{SESSION}_task-{task}_acq-{acq}"
        f"_run-{run}_desc-preproc_eeg.vhdr"
    )
    return vhdr if vhdr.exists() else None


def resolve_photo_events_path(subject: str, task: str, acq: str, run: str) -> Path | None:
    """Return path to photo_events TSV, or None if not found."""
    tsv = (
        PHOTO_EVENTS_ROOT / f"sub-{subject}" / f"ses-{SESSION}" / "eeg"
        / f"sub-{subject}_ses-{SESSION}_task-{task}_acq-{acq}"
          f"_run-{run}_desc-photo_events.tsv"
    )
    return tsv if tsv.exists() else None


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------

def create_epochs_for_run(
    eeg_raw: mne.io.Raw,
    photo_events_df: pd.DataFrame,
    eeg_channels: list[str],
) -> mne.Epochs | None:
    """Build MNE Epochs from photo_events for one run.

    Parameters
    ----------
    eeg_raw : mne.io.Raw
        Preprocessed continuous EEG.
    photo_events_df : pd.DataFrame
        Photo events TSV with CHANGE_PHOTO / NO_CHANGE_PHOTO rows.
    eeg_channels : list[str]
        Channel names to pick.

    Returns
    -------
    mne.Epochs or None
    """
    # Filter to only the photo event rows
    photo_rows = photo_events_df[
        photo_events_df["trial_type"].isin(EVENT_ID.keys())
    ].copy()

    if photo_rows.empty:
        return None

    sfreq = eeg_raw.info["sfreq"]
    available_chs = [ch for ch in eeg_channels if ch in eeg_raw.ch_names]
    if not available_chs:
        return None

    # Build MNE events array: (sample, 0, event_id)
    onsets_s = photo_rows["onset"].astype(float).values
    event_ids = photo_rows["trial_type"].map(EVENT_ID).values

    # Convert onset seconds to sample indices
    samples = np.round(onsets_s * sfreq).astype(int) + eeg_raw.first_samp

    # Filter out events that fall outside the recording
    n_total = eeg_raw.n_times
    last_sample = eeg_raw.first_samp + n_total
    valid = (samples >= eeg_raw.first_samp) & (samples < last_sample)
    samples = samples[valid]
    event_ids = event_ids[valid]

    if len(samples) == 0:
        return None

    mne_events = np.column_stack([
        samples,
        np.zeros(len(samples), dtype=int),
        event_ids,
    ])
    # Sort by sample
    mne_events = mne_events[np.argsort(mne_events[:, 0])]

    # Build event_id dict with only the conditions present in this run
    present_conditions = set(photo_rows["trial_type"].unique())
    run_event_id = {k: v for k, v in EVENT_ID.items() if k in present_conditions}

    try:
        epochs = mne.Epochs(
            eeg_raw,
            events=mne_events,
            event_id=run_event_id,
            tmin=TMIN,
            tmax=TMAX,
            picks=available_chs,
            baseline=BASELINE,
            preload=True,
            verbose=False,
        )
        return epochs
    except Exception as exc:
        print(f"    Could not create epochs: {exc}")
        return None


def run_pipeline(subject: str) -> mne.Epochs | None:
    """Create and concatenate photo-event epochs across all runs."""
    runs = RUNS_CONFIG.get(subject)
    if runs is None:
        print(f"No RUNS_CONFIG for subject {subject}")
        sys.exit(1)

    print("=" * 60)
    print(f"23 — Epoch photo events — sub-{subject}")
    print("=" * 60)

    all_epochs: list[mne.Epochs] = []

    for rc in runs:
        run_id, task, acq = rc["run"], rc["task"], rc["acq"]
        label = f"task-{task}_acq-{acq}_run-{run_id}"

        vhdr = resolve_eeg_path(subject, task, acq, run_id)
        if vhdr is None:
            print(f"  SKIP {label} — EEG not found")
            continue

        tsv_path = resolve_photo_events_path(subject, task, acq, run_id)
        if tsv_path is None:
            print(f"  SKIP {label} — photo_events TSV not found")
            continue

        print(f"  Loading {label} ...")
        raw = mne.io.read_raw_brainvision(str(vhdr), preload=True, verbose=False)
        events_df = pd.read_csv(tsv_path, sep="\t")

        epochs = create_epochs_for_run(raw, events_df, EEG_CHANNELS)
        if epochs is None:
            print(f"    No epochs created for {label}")
            continue

        n_change = sum(1 for e in epochs.events[:, 2] if e == EVENT_ID["CHANGE_PHOTO"])
        n_nc = sum(1 for e in epochs.events[:, 2] if e == EVENT_ID["NO_CHANGE_PHOTO"])
        print(f"    {label}: {n_change} CHANGE + {n_nc} NO_CHANGE")
        all_epochs.append(epochs)

    if not all_epochs:
        print("No epochs created across any run.")
        return None

    grand = mne.concatenate_epochs(all_epochs)
    print(f"\n  Grand total:")
    for cond in EVENT_ID:
        try:
            n = len(grand[cond])
        except KeyError:
            n = 0
        print(f"    {cond}: {n} epochs")

    # Save
    RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
    out_path = RESULTS_ROOT / f"sub-{subject}_photo-epo.fif"
    grand.save(out_path, overwrite=True)
    print(f"\n  Saved: {out_path}")

    return grand


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create MNE Epochs from photo events",
    )
    parser.add_argument("--subject", type=str, required=True)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    run_pipeline(subject=args.subject)
