name: CI

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main, "feature/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: campeones
      - name: Install pip dev dependencies
        run: pip install -e .[dev]
      - name: Install Nox
        run: pip install nox
      - name: Run lint
        run: nox -s lint
      - name: Run type_check
        run: nox -s type_check
      - name: Run tests
        run: nox -s tests
      - name: Build docs
        run: nox -s docs
